/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author PazosRG
 */
public class VistaSelectorSimulador extends javax.swing.JPanel {

    /**
     * Creates new form VistaSelectorSimulador
     */
    public VistaSelectorSimulador() {
        initComponents();
        
        // set imagen comboBox selector de simuladores
        Dimension selectorDimension = new Dimension(400,46);
        setImageLabel(selectorSimuladores, "C:/Users/PazosRG/code/Universae/theoricBuilderResources/InterfazMobile/Desplegable_Off.png", selectorDimension);
        
        // set iconos de añadir pregunta y de información sobre el simulador
        Dimension iconButtonDimension = new Dimension (30,30);
        setImageLabel(anadirPreguntaButton, "C:/Users/PazosRG/code/Universae/theoricBuilderResources/InterfazMobile/Mas_Off.png", iconButtonDimension);
        setImageLabel(simuladorInfoButton, "C:/Users/PazosRG/code/Universae/theoricBuilderResources/InterfazMobile/info_Off.png", iconButtonDimension);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tipoSimuladorLabel = new javax.swing.JLabel();
        selectorSimuladores = new javax.swing.JLabel();
        listaSimuladoresPanel = new javax.swing.JPanel();
        simuladorLabel0 = new javax.swing.JLabel();
        simuladorLabel1 = new javax.swing.JLabel();
        simuladorLabel2 = new javax.swing.JLabel();
        simuladorLabel3 = new javax.swing.JLabel();
        simuladorLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textAnadirPregunta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        anadirPreguntaButton = new javax.swing.JLabel();
        simuladorInfoButton = new javax.swing.JLabel();

        setBackground(new java.awt.Color(10, 38, 72));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 12));

        tipoSimuladorLabel.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        tipoSimuladorLabel.setForeground(new java.awt.Color(247, 247, 247));
        tipoSimuladorLabel.setText("Tipo de Simulador");
        tipoSimuladorLabel.setMaximumSize(new java.awt.Dimension(400, 15));
        tipoSimuladorLabel.setMinimumSize(new java.awt.Dimension(400, 15));
        tipoSimuladorLabel.setPreferredSize(new java.awt.Dimension(400, 15));
        add(tipoSimuladorLabel);

        selectorSimuladores.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        selectorSimuladores.setForeground(new java.awt.Color(247, 247, 247));
        selectorSimuladores.setText("selectedListaSimuladores");
        selectorSimuladores.setMaximumSize(new java.awt.Dimension(400, 16));
        selectorSimuladores.setMinimumSize(new java.awt.Dimension(400, 16));
        selectorSimuladores.setPreferredSize(new java.awt.Dimension(400, 16));
        add(selectorSimuladores);

        listaSimuladoresPanel.setBackground(new java.awt.Color(111, 114, 113));
        listaSimuladoresPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(193, 197, 200), 1, true));
        listaSimuladoresPanel.setMaximumSize(new java.awt.Dimension(400, 32767));
        listaSimuladoresPanel.setMinimumSize(new java.awt.Dimension(400, 0));
        listaSimuladoresPanel.setPreferredSize(new java.awt.Dimension(400, 105));
        listaSimuladoresPanel.setVerifyInputWhenFocusTarget(false);
        listaSimuladoresPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        simuladorLabel0.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        simuladorLabel0.setForeground(new java.awt.Color(247, 247, 247));
        simuladorLabel0.setText("Ahora Aprendo");
        simuladorLabel0.setMaximumSize(new java.awt.Dimension(400, 15));
        simuladorLabel0.setMinimumSize(new java.awt.Dimension(400, 15));
        simuladorLabel0.setPreferredSize(new java.awt.Dimension(400, 15));
        listaSimuladoresPanel.add(simuladorLabel0);

        simuladorLabel1.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        simuladorLabel1.setForeground(new java.awt.Color(247, 247, 247));
        simuladorLabel1.setText("El Cazador");
        simuladorLabel1.setMaximumSize(new java.awt.Dimension(400, 15));
        simuladorLabel1.setMinimumSize(new java.awt.Dimension(400, 15));
        simuladorLabel1.setPreferredSize(new java.awt.Dimension(400, 15));
        listaSimuladoresPanel.add(simuladorLabel1);

        simuladorLabel2.setFont(new java.awt.Font("Raleway", 1, 14)); // NOI18N
        simuladorLabel2.setForeground(new java.awt.Color(247, 247, 247));
        simuladorLabel2.setText("Atrapa los Univercoins");
        simuladorLabel2.setMaximumSize(new java.awt.Dimension(400, 15));
        simuladorLabel2.setMinimumSize(new java.awt.Dimension(400, 15));
        simuladorLabel2.setPreferredSize(new java.awt.Dimension(400, 15));
        listaSimuladoresPanel.add(simuladorLabel2);

        simuladorLabel3.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        simuladorLabel3.setForeground(new java.awt.Color(247, 247, 247));
        simuladorLabel3.setText("BAAM");
        simuladorLabel3.setMaximumSize(new java.awt.Dimension(400, 15));
        simuladorLabel3.setMinimumSize(new java.awt.Dimension(400, 15));
        simuladorLabel3.setPreferredSize(new java.awt.Dimension(400, 15));
        listaSimuladoresPanel.add(simuladorLabel3);

        simuladorLabel4.setFont(new java.awt.Font("Raleway", 0, 14)); // NOI18N
        simuladorLabel4.setForeground(new java.awt.Color(247, 247, 247));
        simuladorLabel4.setText("PiensoPalabra");
        simuladorLabel4.setMaximumSize(new java.awt.Dimension(400, 15));
        simuladorLabel4.setMinimumSize(new java.awt.Dimension(400, 15));
        simuladorLabel4.setPreferredSize(new java.awt.Dimension(400, 15));
        listaSimuladoresPanel.add(simuladorLabel4);

        add(listaSimuladoresPanel);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 100));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 70));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        textAnadirPregunta.setFont(new java.awt.Font("Raleway", 0, 18)); // NOI18N
        textAnadirPregunta.setForeground(new java.awt.Color(247, 247, 247));
        textAnadirPregunta.setText("Añadir una pregunta");
        textAnadirPregunta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(textAnadirPregunta, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        anadirPreguntaButton.setFont(new java.awt.Font("Raleway", 0, 12)); // NOI18N
        anadirPreguntaButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\PazosRG\\code\\Universae\\theoricBuilderResources\\InterfazMobile\\Mas_Off.png")); // NOI18N
        jPanel2.add(anadirPreguntaButton);

        simuladorInfoButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\PazosRG\\code\\Universae\\theoricBuilderResources\\InterfazMobile\\Info_Off.png")); // NOI18N
        jPanel2.add(simuladorInfoButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anadirPreguntaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel listaSimuladoresPanel;
    private javax.swing.JLabel selectorSimuladores;
    private javax.swing.JLabel simuladorInfoButton;
    private javax.swing.JLabel simuladorLabel0;
    private javax.swing.JLabel simuladorLabel1;
    private javax.swing.JLabel simuladorLabel2;
    private javax.swing.JLabel simuladorLabel3;
    private javax.swing.JLabel simuladorLabel4;
    private javax.swing.JLabel textAnadirPregunta;
    private javax.swing.JLabel tipoSimuladorLabel;
    // End of variables declaration//GEN-END:variables

    public static void setImageLabel(JLabel jLabel, String path, Dimension dimension) {
        ImageIcon imageIcon = new ImageIcon(path);
        Icon icon = new ImageIcon( imageIcon.getImage().getScaledInstance((int)(dimension.getWidth()), (int)(dimension.getHeight()), Image.SCALE_SMOOTH));
        jLabel.setIcon(icon);
        jLabel.repaint();
    }
}
